# Generated by Django 4.2.7 on 2023-11-11 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='client',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation_management.client'),
        ),
        migrations.AddField(
            model_name='tour',
            name='final_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation_management.hotel'),
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel_room',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation_management.hotelroom'),
        ),
        migrations.AddField(
            model_name='tour',
            name='initial_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.IntegerField(default=None),
        ),
    ]
