# Generated by Django 4.2.7 on 2023-11-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0003_tour_currency_tour_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='total_price',
            field=models.IntegerField(default=None),
        ),
    ]
