# Generated by Django 4.2.7 on 2023-11-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0005_alter_tour_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
