# Generated by Django 4.2.7 on 2023-11-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0006_alter_tour_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CLP', 'CLP')], max_length=10),
        ),
    ]
