# Generated by Django 4.2.7 on 2023-11-12 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0007_alter_tour_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='hotel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation_management.hotel'),
        ),
    ]
