# Generated by Django 4.2.7 on 2023-11-12 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0008_hotelroom_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='mobilization',
            field=models.CharField(choices=[('auto', 'Auto'), ('van', 'Van'), ('bus', 'Bus')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C')], max_length=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='room_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation_management.client')),
                ('tour', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation_management.tour')),
            ],
        ),
    ]
