# Generated by Django 4.2.7 on 2023-11-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0010_alter_day_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='room_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('doble', 'Doble'), ('triple', 'Triple'), ('quad', 'Quad'), ('queen', 'Queen'), ('king', 'King')], max_length=20),
        ),
    ]
