# Generated by Django 4.2.7 on 2023-11-12 14:24

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0011_alter_hotelroom_room_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='day',
            managers=[
                ('day', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='discount',
            field=models.IntegerField(default=None),
        ),
    ]
