# Generated by Django 4.2.7 on 2023-11-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0012_alter_day_managers_tour_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='total_price',
            new_name='iva',
        ),
        migrations.AddField(
            model_name='tour',
            name='sub_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='total',
            field=models.IntegerField(default=None),
        ),
    ]
