# Generated by Django 4.2.7 on 2023-11-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0013_rename_total_price_tour_iva_tour_sub_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='iva',
            field=models.IntegerField(default=19),
        ),
    ]
