# Generated by Django 4.2.7 on 2023-11-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0014_alter_tour_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='iva_application',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tour',
            name='iva',
            field=models.IntegerField(default=0),
        ),
    ]
