# Generated by Django 4.2.7 on 2023-11-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0015_tour_iva_application_alter_tour_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tour',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tour',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
